function WindCorrelation
% WindCorrelation - plots the correlation of wind farms to the entire fleet
% in Alberta
% 
% References:
%    N/A
%
% Syntax:
%    N/A
%
% Inputs:
%    N/A
%
% Outputs:
%    N/A
%
% Example: 
%    N/A
%
% Other m-files required: none
% Data files required: windByPlant.csv, location.csv
% Subfunctions: none
%
% See also: N/A
% Author: Will Noel
% email: wnoel@ualberta.ca
% Mar 2021; Last revision: 25-Mar-2021
%------------- BEGIN CODE --------------

% Read in .csv datafile and extract date values
gendata  = readtable('windByPlant.csv');

% Define start date for each wind farm
AKE1date = datetime(2003,2,1);
ARD1date = datetime(2010,12,1);
BSR1date = datetime(2014,5,12);
BTR1date = datetime(2007,12,1);
BUL1date = datetime(2015,12,1);
BUL2date = datetime(2015,12,1);
CR1date  = datetime(2000,10,1);
CRR1date = datetime(2012,5,31);
CRR2date = datetime(2020,5,1);
CRE3date = datetime(2001,9,1);
TAB1date = datetime(2007,3,1);
NEP1date = datetime(2010,12,1);
HAL1date = datetime(2012,12,1);
KHW1date = datetime(2006,3,1);
OWF1date = datetime(2015,3,1);
GWW1date = datetime(2006,8,1);
IEW1date = datetime(2004,5,1);
IEW2date = datetime(2007,1,6);
RIV1date = datetime(2020,5,1);
SCR3date = datetime(2006,10,30);
SCR2date = datetime(2004,7,1);
SCR4date = datetime(2011,1,11);
WHT1date = datetime(2019,12,1);

% Find correlation between wind farm and entire fleet after start date
AKE1c = corrcoef(gendata.AKE1(gendata.date >= AKE1date),...
                gendata.hourly_wind(gendata.date >= AKE1date),'Rows','Complete');

ARD1c = corrcoef(gendata.ARD1(gendata.date >= ARD1date),...
                gendata.hourly_wind(gendata.date >= ARD1date),'Rows','Complete');
            
BSR1c = corrcoef(gendata.BSR1(gendata.date >= BSR1date),...
                gendata.hourly_wind(gendata.date >= BSR1date),'Rows','Complete');

BTR1c = corrcoef(gendata.BTR1(gendata.date >= BTR1date),...
                gendata.hourly_wind(gendata.date >= BTR1date),'Rows','Complete');

BUL1c = corrcoef(gendata.BUL1(gendata.date >= BUL1date),...
                gendata.hourly_wind(gendata.date >= BUL1date),'Rows','Complete');

BUL2c = corrcoef(gendata.BUL2(gendata.date >= BUL2date),...
                gendata.hourly_wind(gendata.date >= BUL2date),'Rows','Complete');
            
CR1c  = corrcoef(gendata.CR1(gendata.date >= CR1date),...
                gendata.hourly_wind(gendata.date >= CR1date),'Rows','Complete');

CRR1c = corrcoef(gendata.CRR1(gendata.date >= CRR1date),...
                gendata.hourly_wind(gendata.date >= CRR1date),'Rows','Complete');

CRR2c = corrcoef(gendata.CRR2(gendata.date >= CRR2date),...
                gendata.hourly_wind(gendata.date >= CRR2date),'Rows','Complete');

CRE3c = corrcoef(gendata.CRE3(gendata.date >= CRE3date),...
                gendata.hourly_wind(gendata.date >= CRE3date),'Rows','Complete');
            
TAB1c = corrcoef(gendata.TAB1(gendata.date >= TAB1date),...
                gendata.hourly_wind(gendata.date >= TAB1date),'Rows','Complete');

NEP1c = corrcoef(gendata.NEP1(gendata.date >= NEP1date),...
                gendata.hourly_wind(gendata.date >= NEP1date),'Rows','Complete');

HAL1c = corrcoef(gendata.HAL1(gendata.date >= HAL1date),...
                gendata.hourly_wind(gendata.date >= HAL1date),'Rows','Complete');

KHW1c = corrcoef(gendata.KHW1(gendata.date >= KHW1date),...
                gendata.hourly_wind(gendata.date >= KHW1date),'Rows','Complete');
            
OWF1c  = corrcoef(gendata.OWF1(gendata.date >= OWF1date),...
                gendata.hourly_wind(gendata.date >= OWF1date),'Rows','Complete');

GWW1c = corrcoef(gendata.GWW1(gendata.date >= GWW1date),...
                gendata.hourly_wind(gendata.date >= GWW1date),'Rows','Complete');

IEW1c = corrcoef(gendata.IEW1(gendata.date >= IEW1date),...
                gendata.hourly_wind(gendata.date >= IEW1date),'Rows','Complete');
            
IEW2c = corrcoef(gendata.IEW2(gendata.date >= IEW2date),...
                gendata.hourly_wind(gendata.date >= IEW2date),'Rows','Complete');

RIV1c = corrcoef(gendata.RIV1(gendata.date >= RIV1date),...
                gendata.hourly_wind(gendata.date >= RIV1date),'Rows','Complete');

SCR3c = corrcoef(gendata.SCR3(gendata.date >= SCR3date),...
                gendata.hourly_wind(gendata.date >= SCR3date),'Rows','Complete');

SCR2c = corrcoef(gendata.SCR2(gendata.date >= SCR2date),...
                gendata.hourly_wind(gendata.date >= SCR2date),'Rows','Complete');
            
SCR4c = corrcoef(gendata.SCR4(gendata.date >= SCR4date),...
                gendata.hourly_wind(gendata.date >= SCR4date),'Rows','Complete');

WHT1c = corrcoef(gendata.WHT1(gendata.date >= WHT1date),...
                gendata.hourly_wind(gendata.date >= WHT1date),'Rows','Complete');
            
% Find average capture rate for each wind farm
AKE1p = sum(gendata.AKE1(gendata.date >= AKE1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= AKE1date))...
          ./sum(gendata.AKE1(gendata.date >= AKE1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= AKE1date)...
          .*gendata.hourly_dispatch(gendata.date >= AKE1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= AKE1date)));

ARD1p = sum(gendata.ARD1(gendata.date >= ARD1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= ARD1date))...
          ./sum(gendata.ARD1(gendata.date >= ARD1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= ARD1date)...
          .*gendata.hourly_dispatch(gendata.date >= ARD1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= ARD1date)));
      
BSR1p = sum(gendata.BSR1(gendata.date >= BSR1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= BSR1date))...
          ./sum(gendata.BSR1(gendata.date >= BSR1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= BSR1date)...
          .*gendata.hourly_dispatch(gendata.date >= BSR1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= BSR1date)));

BTR1p = sum(gendata.BTR1(gendata.date >= BTR1date)...
          .*gendata.actual_posted_pool_price(gendata.date >=BTR1date))...
          ./sum(gendata.BTR1(gendata.date >= BTR1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= BTR1date)...
          .*gendata.hourly_dispatch(gendata.date >= BTR1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= BTR1date)));

BUL1p = sum(gendata.BUL1(gendata.date >= BUL1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= BUL1date))...
          ./sum(gendata.BUL1(gendata.date >= BUL1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= BUL1date)...
          .*gendata.hourly_dispatch(gendata.date >= BUL1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= BUL1date)));
      
BUL2p = sum(gendata.BUL2(gendata.date >= BUL2date)...
          .*gendata.actual_posted_pool_price(gendata.date >= BUL2date))...
          ./sum(gendata.BUL2(gendata.date >= BUL2date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= BUL2date)...
          .*gendata.hourly_dispatch(gendata.date >= BUL2date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= BUL2date)));
            
CR1p  = sum(gendata.CR1(gendata.date >= CR1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= CR1date))...
          ./sum(gendata.CR1(gendata.date >= CR1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= CR1date)...
          .*gendata.hourly_dispatch(gendata.date >= CR1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= CR1date)));

CRR1p = sum(gendata.CRR1(gendata.date >= CRR1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= CRR1date))...
          ./sum(gendata.CRR1(gendata.date >= CRR1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= CRR1date)...
          .*gendata.hourly_dispatch(gendata.date >= CRR1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= CRR1date)));

CRR2p = sum(gendata.CRR2(gendata.date >= CRR2date)...
          .*gendata.actual_posted_pool_price(gendata.date >= CRR2date))...
          ./sum(gendata.CRR2(gendata.date >= CRR2date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= CRR2date)...
          .*gendata.hourly_dispatch(gendata.date >= CRR2date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= CRR2date)));

CRE3p = sum(gendata.CRE3(gendata.date >= CRE3date)...
          .*gendata.actual_posted_pool_price(gendata.date >= CRE3date))...
          ./sum(gendata.CRE3(gendata.date >= CRE3date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= CRE3date)...
          .*gendata.hourly_dispatch(gendata.date >= CRE3date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= CRE3date)));
            
TAB1p = sum(gendata.TAB1(gendata.date >= TAB1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= TAB1date))...
          ./sum(gendata.TAB1(gendata.date >= TAB1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= TAB1date)...
          .*gendata.hourly_dispatch(gendata.date >= TAB1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= TAB1date)));

NEP1p = sum(gendata.NEP1(gendata.date >= NEP1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= NEP1date))...
          ./sum(gendata.NEP1(gendata.date >= NEP1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= NEP1date)...
          .*gendata.hourly_dispatch(gendata.date >= NEP1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= NEP1date)));

HAL1p = sum(gendata.HAL1(gendata.date >= HAL1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= HAL1date))...
          ./sum(gendata.HAL1(gendata.date >= HAL1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= HAL1date)...
          .*gendata.hourly_dispatch(gendata.date >= HAL1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= HAL1date)));

KHW1p = sum(gendata.KHW1(gendata.date >= KHW1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= KHW1date))...
          ./sum(gendata.KHW1(gendata.date >= KHW1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= KHW1date)...
          .*gendata.hourly_dispatch(gendata.date >= KHW1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= KHW1date)));
            
OWF1p  = sum(gendata.OWF1(gendata.date >= OWF1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= OWF1date))...
          ./sum(gendata.OWF1(gendata.date >= OWF1date))...
          ./(...
         sum(gendata.actual_posted_pool_price(gendata.date >= OWF1date)...
          .*gendata.hourly_dispatch(gendata.date >= OWF1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= OWF1date)));

GWW1p = sum(gendata.GWW1(gendata.date >= GWW1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= GWW1date))...
          ./sum(gendata.GWW1(gendata.date >= GWW1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= GWW1date)...
          .*gendata.hourly_dispatch(gendata.date >= GWW1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= GWW1date)));

IEW1p = sum(gendata.IEW1(gendata.date >= IEW1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= IEW1date))...
          ./sum(gendata.IEW1(gendata.date >= IEW1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= IEW1date)...
          .*gendata.hourly_dispatch(gendata.date >= IEW1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= IEW1date)));
            
IEW2p = sum(gendata.IEW2(gendata.date >= IEW2date)...
          .*gendata.actual_posted_pool_price(gendata.date >= IEW2date))...
          ./sum(gendata.IEW2(gendata.date >= IEW2date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= IEW2date)...
          .*gendata.hourly_dispatch(gendata.date >= IEW2date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= IEW2date)));

RIV1p = sum(gendata.RIV1(gendata.date >= RIV1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= RIV1date))...
          ./sum(gendata.RIV1(gendata.date >= RIV1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= RIV1date)...
          .*gendata.hourly_dispatch(gendata.date >= RIV1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= RIV1date)));

SCR3p = sum(gendata.SCR3(gendata.date >= SCR3date)...
          .*gendata.actual_posted_pool_price(gendata.date >= SCR3date))...
          ./sum(gendata.SCR3(gendata.date >= SCR3date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= SCR3date)...
          .*gendata.hourly_dispatch(gendata.date >= SCR3date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= SCR3date)));

SCR2p = sum(gendata.SCR2(gendata.date >= SCR2date)...
          .*gendata.actual_posted_pool_price(gendata.date >= SCR2date))...
          ./sum(gendata.SCR2(gendata.date >= SCR2date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= SCR2date)...
          .*gendata.hourly_dispatch(gendata.date >= SCR2date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= SCR2date)));
            
SCR4p = sum(gendata.SCR4(gendata.date >= SCR4date)...
          .*gendata.actual_posted_pool_price(gendata.date >= SCR4date))...
          ./sum(gendata.SCR4(gendata.date >= SCR4date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= SCR4date)...
          .*gendata.hourly_dispatch(gendata.date >= SCR4date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= SCR4date)));

WHT1p = sum(gendata.WHT1(gendata.date >= WHT1date)...
          .*gendata.actual_posted_pool_price(gendata.date >= WHT1date))...
          ./sum(gendata.WHT1(gendata.date >= WHT1date))...
          ./(...
        sum(gendata.actual_posted_pool_price(gendata.date >= WHT1date)...
          .*gendata.hourly_dispatch(gendata.date >= WHT1date))...
          ./sum(gendata.hourly_dispatch(gendata.date >= WHT1date)));

% Combine correlation results into one vector
corrPlot = [AKE1c(1,2) ARD1c(1,2) BSR1c(1,2) BTR1c(1,2) BUL1c(1,2) ...
            BUL2c(1,2) CR1c(1,2) CRE3c(1,2) CRR1c(1,2) CRR2c(1,2)  ...
            GWW1c(1,2) HAL1c(1,2) IEW1c(1,2) IEW2c(1,2) KHW1c(1,2) ... 
            NEP1c(1,2) OWF1c(1,2) RIV1c(1,2) SCR2c(1,2) SCR3c(1,2) ...
            SCR4c(1,2) TAB1c(1,2) WHT1c(1,2)];
        
cappPlot = [AKE1p ARD1p BSR1p BTR1p BUL1p ...
            BUL2p CR1p CRE3p CRR1p CRR2p  ...
            GWW1p HAL1p IEW1p IEW2p KHW1p ... 
            NEP1p OWF1p RIV1p SCR2p SCR3p ...
            SCR4p TAB1p WHT1p];
        
datePlot = [AKE1date ARD1date BSR1date BTR1date BUL1date ...
            BUL2date CR1date CRE3date CRR1date CRR2date  ...
            GWW1date HAL1date IEW1date IEW2date KHW1date ... 
            NEP1date OWF1date RIV1date SCR2date SCR3date ...
            SCR4date TAB1date WHT1date];
        
% Sort in descending order of correlation
[corrPlot2, order] = sort(corrPlot,'descend'); 
cappPlot2          = cappPlot(order);
datePlot2          = datePlot(order);
mindate            = min(datePlot);
maxdate            = max(datePlot);
        
% Figure x labels
xlbl = gendata.Properties.VariableNames(6:end);
xlbl = xlbl(order);

% Plot figure
set(gcf,'Units','inches','Position',[1 1 6.75 3]); % [xpos ypos width height]
set(gcf,'DefaultTextInterpreter','latex');
set(gcf,'DefaultAxesTickLabelInterpreter','latex');
set(gca,'DefaultAxesTickLabelInterpreter','latex','FontSize',9);
yyaxis left
b = bar(corrPlot2,'FaceColor','flat','EdgeColor',[0.5 0.5 0.5]); hold on
    xticks(1:length(xlbl));
    xticklabels(xlbl);
    xtickangle(35);
    ylim([0 1]);
    ylabel({'Wind Farm Average Value Factor (bar)';'\& Correlation to Fleet Output (scatter)'});
    for i = 1:length(datePlot2)
        b.CData(i,:) = (maxdate-datePlot2(i))./(maxdate-mindate).*[1 1 1];
    end
yyaxis right
p = plot(cappPlot2,'ko','MarkerFaceColor','w');
    ax = gca;
    yticks(0:0.2:1);
    yticklabels({});
    ylim([0 1]);
    ax.YAxis(1).Color = 'k';
    ax.YAxis(2).Color = 'k';
    box(ax,'off');
    
% Add colour bar
clr = colorbar;
clr.Location = 'north';
clr.FontSize = 10;
clr.Label.Interpreter = 'latex';
clr.Label.String = '\textbf{Comission Date (2000 - 2020)}';
clr.Label.FontSize = 10;
clr.XAxisLocation = 'bottom';
clr.TickLabelInterpreter = 'latex';
clr.Ticks = [];
clr.TickLabels = [];
colormap(flipud(gray));

hold off

    
% legend([p b],'Capture Rate','Correlation','location','SouthOutside',...
%     'Interpreter','Latex');
% legend box off






















